// Copyright Epic Games, Inc. All Rights Reserved.

#include "K2Node_MetaStoryBlueprintPropertyRef.h"
#include "MetaStoryPropertyRef.h"
#include "Blueprint/MetaStoryNodeBlueprintBase.h"
#include "EdGraphSchema_K2.h"
#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "K2Node_VariableGet.h"
#include "MetaStoryPropertyRefHelpers.h"
#include "KismetCompiledFunctionContext.h"
#include "EdGraphUtilities.h"

#include UE_INLINE_GENERATED_CPP_BY_NAME(K2Node_MetaStoryBlueprintPropertyRef)

#define LOCTEXT_NAMESPACE "K2Node_MetaStoryBlueprintPropertyRef"

namespace UE::MetaStory::BlueprintPropertyRef
{
	const FName PropertyRefPinName(TEXT("PropertyRef"));

	const FName SucceededExecPinName(TEXT("Succeeded"));
	const FName FailedExecPinName(TEXT("Failed"));

	const FName OutReferencePinName(TEXT("Reference"));
}

void UK2Node_MetaStoryBlueprintPropertyRef::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, FMetaStoryBlueprintPropertyRef::StaticStruct(), UE::MetaStory::BlueprintPropertyRef::PropertyRefPinName);

	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UE::MetaStory::BlueprintPropertyRef::SucceededExecPinName);
    CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UE::MetaStory::BlueprintPropertyRef::FailedExecPinName);

	UEdGraphNode::FCreatePinParams OutPinParams;
	OutPinParams.bIsReference = true;
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Wildcard, UE::MetaStory::BlueprintPropertyRef::OutReferencePinName, OutPinParams);
}

FText UK2Node_MetaStoryBlueprintPropertyRef::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	return LOCTEXT("NodeTitle", "Get Property Reference");
}

FText UK2Node_MetaStoryBlueprintPropertyRef::GetTooltipText() const
{
	return LOCTEXT("NodeTooltip", "Returns bound property reference.");
}

FText UK2Node_MetaStoryBlueprintPropertyRef::GetMenuCategory() const
{
	return LOCTEXT("NodeCategory", "MetaStory|PropertyRef");
}

void UK2Node_MetaStoryBlueprintPropertyRef::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	Super::GetMenuActions(ActionRegistrar);
	UClass* Action = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(Action))
    {
        UBlueprintNodeSpawner* Spawner = UBlueprintNodeSpawner::Create(Action);
        ActionRegistrar.AddBlueprintAction(Action, Spawner);
    }
}

void UK2Node_MetaStoryBlueprintPropertyRef::ReconstructNode()
{
	Super::ReconstructNode();
	UpdateOutputPin();
}

void UK2Node_MetaStoryBlueprintPropertyRef::ClearCachedBlueprintData(UBlueprint* Blueprint)
{
	Super::ClearCachedBlueprintData(Blueprint);
	Modify(true);
	UpdateOutputPin();
}

void UK2Node_MetaStoryBlueprintPropertyRef::ValidateNodeDuringCompilation(FCompilerResultsLog& MessageLog) const
{
	Super::ValidateNodeDuringCompilation(MessageLog);

	const UClass* BlueprintClass = GetBlueprintClassFromNode();
	if (!BlueprintClass->IsChildOf<UMetaStoryNodeBlueprintBase>())
	{
		const FText ErrorText = LOCTEXT("InvalidSelfType", "This blueprint (self) is not a 'MetaStory Blueprint Node'.");
		MessageLog.Error(*ErrorText.ToString(), this);
	}
}

void UK2Node_MetaStoryBlueprintPropertyRef::UpdateOutputPin() const
{
	UEdGraphPin& OutValuePin = *FindPinChecked(UE::MetaStory::BlueprintPropertyRef::OutReferencePinName);
	const UEdGraphPin& PropertyRefPin = *FindPinChecked(UE::MetaStory::BlueprintPropertyRef::PropertyRefPinName);

	const UBlueprint* Blueprint = FBlueprintEditorUtils::FindBlueprintForNodeChecked(this);
	if (Blueprint && Blueprint->GeneratedClass && PropertyRefPin.LinkedTo.Num() == 1)
	{
		UK2Node_VariableGet* VariableGet = Cast<UK2Node_VariableGet>(PropertyRefPin.LinkedTo[0]->GetOwningNode());
		if (VariableGet)
		{
			UObject* CDO = Blueprint->GeneratedClass->GetDefaultObject<UObject>();
			FProperty* Property = Blueprint->GeneratedClass->FindPropertyByName(VariableGet->VariableReference.GetMemberName());
			FStructProperty* StructProperty = CastField<FStructProperty>(Property);
			if (StructProperty && StructProperty->Struct == FMetaStoryBlueprintPropertyRef::StaticStruct())
			{
				FMetaStoryBlueprintPropertyRef PropertyRef;
				Property->GetValue_InContainer(CDO, &PropertyRef);
				FEdGraphPinType PinType = UE::MetaStory::PropertyRefHelpers::GetBlueprintPropertyRefInternalTypeAsPin(PropertyRef);

				PinType.bIsReference = true;
				OutValuePin.PinType = PinType;
				GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(&OutValuePin);
				return;
			}
		}
	}

	FCreatePinParams PinParams{};
	OutValuePin.PinType = FEdGraphPinType(UEdGraphSchema_K2::PC_Wildcard, NAME_None, nullptr, PinParams.ContainerType, PinParams.bIsReference, PinParams.ValueTerminalType);
}

void FKCHandler_MetaStoryBlueprintPropertyRefGet::RegisterNets(FKismetFunctionContext& Context, UEdGraphNode* Node)
{
	const UK2Node_MetaStoryBlueprintPropertyRef* GetRefNode = CastChecked<UK2Node_MetaStoryBlueprintPropertyRef>(Node);

	UEdGraphPin* OutPin = GetRefNode->FindPinChecked(UE::MetaStory::BlueprintPropertyRef::OutReferencePinName);
	FBPTerminal* OutValueTerminal = new FBPTerminal();
	Context.InlineGeneratedValues.Add(OutValueTerminal);
	OutValueTerminal->CopyFromPin(OutPin, Context.NetNameMap->MakeValidName(OutPin));
	Context.NetMap.Add(OutPin, OutValueTerminal);

	FBPTerminal* BoolTerm = Context.CreateLocalTerminal();
	BoolTerm->Type.PinCategory = UEdGraphSchema_K2::PC_Boolean;
	BoolTerm->Source = Node;
	BoolTerm->Name = Context.NetNameMap->MakeValidName(Node, TEXT("ReferenceValid"));
	TemporaryBoolTerminals.Add(Node, BoolTerm);
}

void FKCHandler_MetaStoryBlueprintPropertyRefGet::Compile(FKismetFunctionContext& Context, UEdGraphNode* Node)
{
	const UK2Node_MetaStoryBlueprintPropertyRef* GetRefNode = CastChecked<UK2Node_MetaStoryBlueprintPropertyRef>(Node);
   
    UEdGraphPin* PropertyRefPin = GetRefNode->FindPinChecked(UE::MetaStory::BlueprintPropertyRef::PropertyRefPinName);
    FBPTerminal* PropertyRefTerminal = Context.NetMap.FindRef(FEdGraphUtilities::GetNetFromPin(PropertyRefPin));
	check(PropertyRefTerminal);
    
	const UEdGraphPin* OutPin = GetRefNode->FindPinChecked(UE::MetaStory::BlueprintPropertyRef::OutReferencePinName);
    FBPTerminal* OutTerminal = Context.NetMap.FindRef(OutPin);
	check(OutTerminal);

	FBlueprintCompiledStatement* GetRef = new FBlueprintCompiledStatement();
	GetRef->Type = KCST_CallFunction;
	GetRef->FunctionToCall = UMetaStoryNodeBlueprintBase::StaticClass()->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMetaStoryNodeBlueprintBase, GetPropertyReference));
	GetRef->FunctionContext = nullptr;
	GetRef->RHS.Add(PropertyRefTerminal);

    OutTerminal->InlineGeneratedParameter = GetRef;
	OutTerminal->bPassedByReference = true;

	FBPTerminal* IsValidTerminal = TemporaryBoolTerminals.FindChecked( Node);
	FBlueprintCompiledStatement& HasPropertyFunction = Context.AppendStatementForNode(Node);
	HasPropertyFunction.Type = KCST_CallFunction;
	HasPropertyFunction.FunctionToCall = UMetaStoryNodeBlueprintBase::StaticClass()->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMetaStoryNodeBlueprintBase, IsPropertyRefValid));
	HasPropertyFunction.FunctionContext = nullptr;
	HasPropertyFunction.LHS = IsValidTerminal;
	HasPropertyFunction.RHS.Add(PropertyRefTerminal);

	FBlueprintCompiledStatement& OnInvalidRef = Context.AppendStatementForNode(Node);
	OnInvalidRef.Type = KCST_GotoIfNot;
	OnInvalidRef.LHS = IsValidTerminal;
	Context.GotoFixupRequestMap.Add(&OnInvalidRef, GetRefNode->FindPinChecked(UE::MetaStory::BlueprintPropertyRef::FailedExecPinName));

	FBlueprintCompiledStatement& OnValidRef = Context.AppendStatementForNode(Node);
	OnValidRef.Type = KCST_UnconditionalGoto;
	OnValidRef.LHS = IsValidTerminal;
	Context.GotoFixupRequestMap.Add(&OnValidRef, GetRefNode->FindPinChecked(UE::MetaStory::BlueprintPropertyRef::SucceededExecPinName));
}

#undef LOCTEXT_NAMESPACE
